CODE_MISSION_TEMPLATE = [
    {
        "frame": 10,
        "command": 22,
        "param1": 0,
        "param2": 0,
        "param3": 0,
        "param4": 0,
        "x": 0,
        "y": 0,
        "z": 3,
    },
    {
        "frame": 10,
        "command": 19,
        "param1": 5,
        "param2": 2,
        "param3": 1,
        "param4": 0,
        "x": 0,
        "y": 0,
        "z": 0,
    },
    {
        "frame": 10,
        "command": 21,
        "param1": 0,
        "param2": 1,
        "param3": 0,
        "param4": 0,
        "x": 0,
        "y": 0,
        "z": 0,
    },
]
