// MAVLink constants
export const MAVLinkModes = {
  QUAD_STABILIZE: 0,
  QUAD_ACRO: 1,
  QUAD_ALT_HOLD: 2,
  QUAD_AUTO: 3,
  QUAD_GUIDED: 4,
  QUAD_LOITER: 5,
  QUAD_RTL: 6,
  QUAD_CIRCLE: 7,
  QUAD_LAND: 9,
  QUAD_DRIFT: 11,
  QUAD_SPORT: 13,
  QUAD_FLIP: 14,
  QUAD_AUTOTUNE: 15,
  QUAD_POSHOLD: 16,
  QUAD_BRAKE: 17,
  QUAD_THROW: 18,
  QUAD_AVOID_ADSB: 19,
  QUAD_GUIDED_NOGPS: 20,
} as const;

export const MAVLinkCommands = {
  NAV_WAYPOINT: 16,
  NAV_LOITER_UNLIM: 17,
  NAV_LOITER_TURNS: 18,
  NAV_LOITER_TIME: 19,
  NAV_RETURN_TO_LAUNCH: 20,
  NAV_LAND: 21,
  NAV_TAKEOFF: 22,
  CONDITION_DELAY: 112,
  CONDITION_CHANGE_ALT: 113,
} as const;

export const GPSFixType = {
  NO_GPS: 0,
  NO_FIX: 1,
  GPS_FIX_2D: 2,
  GPS_FIX_3D: 3,
  GPS_FIX_DGPS: 4,
  GPS_FIX_RTK_FLOAT: 5,
  GPS_FIX_RTK_FIXED: 6,
  GPS_FIX_STATIC: 7,
} as const;
